#!/usr/bin/env node
// Generates supabase/seed.sql from the MVP HTML guide (docs/mvp/call-center-guide-mvp.html).
// The MVP is the source of truth for the initial data; after go-live the admin
// panel becomes the source of truth and this script is only for fresh setups.
//
// Usage: node scripts/extract-mvp.mjs [path/to/mvp.html] > supabase/seed.sql
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const htmlPath = process.argv[2] || path.join(root, 'docs/mvp/call-center-guide-mvp.html');
const lines = fs.readFileSync(htmlPath, 'utf8').split('\n');

// ---------------------------------------------------------------------
// 1) Pull the pure-data parts of the MVP scripts and evaluate them.
// ---------------------------------------------------------------------
const indexOf = (re, from = 0) => {
  for (let i = from; i < lines.length; i++) if (re.test(lines[i])) return i;
  throw new Error('marker not found: ' + re);
};
const slice = (a, b) => lines.slice(a, b).join('\n');

const dataStart = indexOf(/^const DEFS = \{/);
const dataEnd = indexOf(/^let currentBranch/);
const wfStart = indexOf(/^const SERVICES = \[/);
const wfEnd = indexOf(/^function toggleArea/);
const rulesStart = indexOf(/^const RULES = \{/);
const rulesEnd = indexOf(/^const ruleOf/);

const MANUAL_KEYS = [
  'GOLDEN_RULES', 'MEDICAL_BOUNDARY', 'PRIVACY_RULES', 'VOICE_TABLE', 'EMPATHY_TABLE',
  'REPLACE_TABLE', 'CALL_STEPS', 'SCENARIOS', 'OBJECTIONS', 'OUTBOUND', 'OUTBOUND_RULES',
  'ESCALATION_MATRIX', 'HANDOVER_CARD', 'CONTACTS', 'QA_SCORECARD', 'CRITICAL_ERRORS',
  'KPIS', 'STATUS_MEANINGS', 'GLOSSARY', 'FILLER_BRAND_NOTES',
];

const code = [
  'const escapeHtml = s => String(s);',
  slice(dataStart, dataEnd),
  slice(wfStart, wfEnd),
  slice(rulesStart, rulesEnd),
  `;({ DEFS, CATEGORY_INFO, CHIP_TO_SERVICE22, SERVICES22, DAYS, SHARED_PRICE_CATEGORIES,
      NEWCAIRO_PRICE_CATEGORIES, DATA, BRANCH_LABELS, SERVICES, LASER_WOMEN, LASER_MEN,
      AREA_CONFLICTS, RULES, BRANCH_RULES, ${MANUAL_KEYS.join(', ')} })`,
].join('\n');

const M = vm.runInNewContext(code, { document: {}, window: {} });

// ---------------------------------------------------------------------
// 2) Helpers
// ---------------------------------------------------------------------
const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const qArr = (arr) => (arr && arr.length ? `array[${arr.map(q).join(', ')}]::text[]` : `'{}'::text[]`);
const qJson = (v) => `${q(JSON.stringify(v))}::jsonb`;
const slug = (n) => String(n || '').toLowerCase().replace(/^dr\.?\s+/, '').replace(/[^a-z؀-ۿ]/g, '');
const stripTags = (s) => String(s).replace(/<[^>]+>/g, '');
const arDigits = (s) => String(s).replace(/[٠-٩]/g, (d) => '٠١٢٣٤٥٦٧٨٩'.indexOf(d));
const branchId = (bk) => `(select id from public.branches where code = ${q(bk)})`;
const doctorId = (bk, dc) =>
  `(select id from public.doctors where code = ${q(dc)} and branch_id = ${branchId(bk)})`;
const toTime = (min) => `${String(Math.floor(min / 60)).padStart(2, '0')}:${String(min % 60).padStart(2, '0')}`;

// Same parser as the MVP engine (parseDay).
const SHIFT_RE = /(\d{1,2})(?::(\d{2}))?\s*(AM|PM)\s*[–\-]\s*(\d{1,2})(?::(\d{2}))?\s*(AM|PM)(.*)$/i;
const h12 = (h, m, ap) => { let x = (+h) % 12; if (/pm/i.test(ap)) x += 12; return x * 60 + (+m || 0); };
function parseDay(val) {
  if (!val) return [];
  return String(val).split(/\n/).map((line) => {
    const m = line.match(SHIFT_RE);
    if (!m) return null;
    const rest = m[7] || '';
    let kind = 'all';
    if (/ليزر/.test(rest)) kind = 'laser';
    else if (/باقي الخدمات|خدمات أخرى|خدمات اخرى/.test(rest)) kind = 'other';
    else if (/جلدية/.test(rest)) kind = 'derma';
    return { from: h12(m[1], m[2], m[3]), to: h12(m[4], m[5], m[6]), kind };
  }).filter(Boolean);
}
const priceNum = (p) => {
  const n = parseFloat(String(p).replace(/[^\d.]/g, ''));
  return Number.isFinite(n) ? n : null;
};

const out = [];
const emit = (s = '') => out.push(s);
const warn = (s) => process.stderr.write('warn: ' + s + '\n');

emit('-- =====================================================================');
emit('-- GENERATED by scripts/extract-mvp.mjs from docs/mvp/call-center-guide-mvp.html');
emit('-- Do not edit by hand — change the generator or use the admin panel.');
emit('-- =====================================================================');
emit('begin;');
emit();

// ---------------------------------------------------------------------
// 3) Price lists + catalogue
// ---------------------------------------------------------------------
const PRICE_LISTS = {
  standard: { name: 'الأسعار الموحدة (كل الفروع)', cats: M.SHARED_PRICE_CATEGORIES },
  new_cairo: { name: 'أسعار القاهرة الجديدة', cats: M.NEWCAIRO_PRICE_CATEGORIES },
};
const plId = (c) => `(select id from public.price_lists where code = ${q(c)})`;
const catId = (pl, name) => `(select id from public.price_categories where price_list_id = ${plId(pl)} and name = ${q(name)})`;
const itemId = (pl, cat, name) => `(select id from public.price_items where category_id = ${catId(pl, cat)} and name = ${q(name)})`;

emit('-- Price lists');
for (const [pc, pl] of Object.entries(PRICE_LISTS)) {
  emit(`insert into public.price_lists (code, name) values (${q(pc)}, ${q(pl.name)});`);
  pl.cats.forEach((cat, ci) => {
    const info = M.CATEGORY_INFO[cat.cat] || {};
    const def = info.defKey ? M.DEFS[info.defKey] : null;
    const note = info.priceNote || (def && def.priceNote) || null;
    emit(`insert into public.price_categories (price_list_id, name, info_note, kb_slug, sort) values (${plId(pc)}, ${q(cat.cat)}, ${q(note)}, ${q(info.defKey ? 'def:' + info.defKey : null)}, ${ci});`);
    cat.items.forEach(([name, price], ii) => {
      const n = priceNum(price);
      emit(`insert into public.price_items (category_id, name, price, price_text, sort) values (${catId(pc, cat.cat)}, ${q(name)}, ${n === null ? 'null' : n}, ${n === null ? q(price) : 'null'}, ${ii});`);
    });
  });
}
emit();

// ---------------------------------------------------------------------
// 4) Services (wizard list + 3 services the MVP wizard did not have)
// ---------------------------------------------------------------------
const SERVICES = M.SERVICES.concat([
  { id: 'vivace', ar: 'فيفاتشي VIVACE', en: 'Vivace', match: /^vivace$/i },
  { id: 'gcell', ar: 'G-Cell (بديل زراعة الشعر)', en: 'G-Cell', match: /^g-cell$/i },
  { id: 'dental', ar: 'أسنان', en: 'Dental', match: /^dental$/i },
]);
emit('-- Services');
SERVICES.forEach((s, i) => {
  const kb = M.CHIP_TO_SERVICE22[s.en] ? 'service:' + M.CHIP_TO_SERVICE22[s.en]
    : s.id === 'consult' ? 'service:derma_consult' : s.def ? 'def:' + s.def : null;
  emit(`insert into public.services (code, name_ar, name_en, default_duration_min, uses_laser_areas, kb_slug, sort) values (${q(s.id)}, ${q(s.ar)}, ${q(s.en)}, 30, ${s.id === 'laser'}, ${q(kb)}, ${i});`);
});
emit();

// ---------------------------------------------------------------------
// 5) Laser areas, conflicts, combos, price map
// ---------------------------------------------------------------------
emit('-- Laser areas');
const AREAS = M.LASER_WOMEN.map((a) => ({ ...a, gender: 'female' }))
  .concat(M.LASER_MEN.map((a) => ({ ...a, gender: 'male' })));
AREAS.forEach((a, i) => {
  emit(`insert into public.laser_areas (code, gender, name_en, hint_ar, duration_min, is_small, is_full_body, requires_companion, sort) values (${q(a.id)}, ${q(a.gender)}, ${q(a.ar)}, ${q(a.hint)}, ${a.min || 0}, ${!!a.small}, ${!!a.fb}, ${!!a.needsOther}, ${i});`);
});
for (const [a, list] of Object.entries(M.AREA_CONFLICTS)) {
  for (const b of list) {
    emit(`insert into public.laser_area_conflicts (area_code, conflicts_with) values (${q(a)}, ${q(b)}) on conflict do nothing;`);
  }
}
emit(`insert into public.laser_area_combos (label, required_codes, any_of_codes, duration_adjust_min, sort) values
  ('كومبو Half-Legs + Half-Arms = ٣٠ دقيقة', array['w_halfarms'], array['w_halflegup','w_halflegdn'], -30, 0),
  ('كومبو Under Arms + Bikini + Bikini Line = ٣٠ دقيقة', array['w_underarm','w_bikini','w_bikiniline'], '{}', 0, 1);`);

// Price map: bundles (from the MVP pricing logic) + single areas.
const LASER_WOMEN_CAT = 'Laser - إزالة الشعر بالمنطقة';
const LASER_MEN_CAT = 'إزالة الشعر للرجال (Laser - Men)';
const BUNDLES = [
  { codes: ['w_underarm', 'w_bikini'], cat: LASER_WOMEN_CAT, name: { standard: 'البكيني والأندر أرم (Bikini & Underarms)', new_cairo: 'البكيني والأندر أرم (Bikini & Underarms)' } },
  { codes: ['w_face', 'w_neck'], cat: LASER_WOMEN_CAT, name: { standard: 'الوجه والرقبة (Face & Neck)', new_cairo: 'الوجه والرقبة (Face & Neck)' } },
  { codes: ['m_chest', 'm_back'], cat: LASER_MEN_CAT, name: { standard: 'الصدر والضهر كامل (Full Chest & Back)', new_cairo: 'الصدر والضهر كامل (Full Chest & Back)' } },
];
emit('-- Laser price map');
for (const pc of Object.keys(PRICE_LISTS)) {
  const cats = PRICE_LISTS[pc].cats;
  const has = (cat, name) => !!(cats.find((c) => c.cat === cat) || { items: [] }).items.find((it) => it[0] === name);
  const addMap = (codes, cat, name) => {
    if (!has(cat, name)) { warn(`price item missing: [${pc}] ${cat} / ${name}`); return; }
    const pkg = name + ' - باكدج 3 جلسات';
    emit(`insert into public.laser_price_map (price_list_id, area_codes, single_item_id, package3_item_id) values (${plId(pc)}, ${qArr(codes)}, ${itemId(pc, cat, name)}, ${has(cat, pkg) ? itemId(pc, cat, pkg) : 'null'});`);
  };
  BUNDLES.forEach((b) => addMap(b.codes, b.cat, b.name[pc]));
  AREAS.forEach((a) => {
    if (!a.p) return;
    const name = typeof a.p === 'string' ? a.p : pc === 'new_cairo' ? a.p.n : a.p.s;
    addMap([a.id], a.gender === 'male' ? LASER_MEN_CAT : LASER_WOMEN_CAT, name);
  });
}
emit();

// ---------------------------------------------------------------------
// 6) Branches, policies, services, consultations
// ---------------------------------------------------------------------
const POLICIES = {
  tanta1: { auto_confirm_weekdays: [0] },          // Saturday: we confirm Open doctors
  tanta2: { same_day_always_request: true },
  shebin: { allow_overlap: false },
};
const CONSULT_KIND = { 'Cons Derma': 'derma', 'Cons Hair': 'hair', 'Cons Derma & Hair': 'derma_hair', 'Re Cons': 'recons', Pulse: 'pulse' };

emit('-- Branches');
Object.keys(M.BRANCH_LABELS).forEach((bk, i) => {
  const b = M.DATA[bk];
  emit(`insert into public.branches (code, name_ar, address, payment_methods, managers, price_list_id, sort) values (${q(bk)}, ${q(b.name)}, ${q(b.address)}, ${qArr(b.payment)}, ${qArr(b.managers)}, ${plId(bk === 'newcairo' ? 'new_cairo' : 'standard')}, ${i});`);
  const p = POLICIES[bk] || {};
  emit(`insert into public.branch_policies (branch_id, request_window_days, same_day_always_request, auto_confirm_weekdays, allow_overlap, booking_rules) values (${branchId(bk)}, 1, ${!!p.same_day_always_request}, ${p.auto_confirm_weekdays ? `array[${p.auto_confirm_weekdays.join(',')}]::smallint[]` : `'{}'::smallint[]`}, ${p.allow_overlap !== false}, ${qArr(b.bookingRules.map(stripTags))});`);
  const brr = M.BRANCH_RULES[bk];
  if (brr && brr.laserCutoff) {
    brr.laserCutoff.days.forEach((day) => {
      emit(`insert into public.branch_laser_cutoffs (branch_id, weekday, shift_starts_before, cutoff) values (${branchId(bk)}, ${M.DAYS.indexOf(day)}, ${q(brr.laserCutoff.before)}, ${q(brr.laserCutoff.at)});`);
    });
  }
  SERVICES.forEach((s) => {
    const offered = s.id === 'consult' || b.services.some((x) => s.match.test(x));
    if (offered) emit(`insert into public.branch_services (branch_id, service_id) values (${branchId(bk)}, (select id from public.services where code = ${q(s.id)}));`);
  });
  b.services.forEach((x) => { if (!SERVICES.some((s) => s.match && s.match.test(x))) warn(`[${bk}] service chip not mapped: ${x}`); });
  b.consultations.forEach((c) => {
    const kind = CONSULT_KIND[c.name];
    if (!kind) { warn(`[${bk}] consultation not mapped: ${c.name}`); return; }
    emit(`insert into public.consultation_prices (branch_id, doctor_id, kind, price) values (${branchId(bk)}, null, ${q(kind)}, ${priceNum(c.price)});`);
  });
});
emit();

// ---------------------------------------------------------------------
// 7) Doctors, schedules, constraints, per-doctor consultation prices
// ---------------------------------------------------------------------
emit('-- Doctors');
const usedRules = new Set();
Object.keys(M.BRANCH_LABELS).forEach((bk) => {
  M.DATA[bk].doctors.forEach((d, di) => {
    const dc = slug(d.name);
    const key = bk + ':' + dc;
    const r = M.RULES[key] || {};
    if (M.RULES[key]) usedRules.add(key);
    const notes = [d.notes, r.note].filter(Boolean).join(' — ') || null;
    emit(`insert into public.doctors (branch_id, code, display_name, person_key, default_booking_status, accepts_men, laser_men_allowed, men_laser_area_codes, rejects_small_areas_only, no_overlap, notes, sort) values (${branchId(bk)}, ${q(dc)}, ${q(d.name)}, ${q(dc)}, ${q(r.status === 'Open' ? 'open' : 'confirmed')}, ${!r.noMen}, ${!r.noLaserMen}, ${r.menLaserAreas ? qArr(r.menLaserAreas) : 'null'}, ${!!r.noSmallAreas}, ${!!r.noOverlapEver}, ${q(notes)}, ${di});`);

    for (const [day, val] of Object.entries(d.week || {})) {
      const wd = M.DAYS.indexOf(day);
      const segs = parseDay(val);
      if (!segs.length && val && !/إجازة/.test(val)) warn(`[${key}] unparsed schedule "${day}": ${val}`);
      segs.forEach((s) => {
        emit(`insert into public.doctor_schedules (doctor_id, weekday, start_time, end_time, kind) values (${doctorId(bk, dc)}, ${wd}, ${q(toTime(s.from))}, ${q(toTime(s.to))}, ${q(s.kind)});`);
      });
    }
    for (const [day, t] of Object.entries(r.laserCutoff || {})) {
      emit(`insert into public.doctor_laser_cutoffs (doctor_id, weekday, cutoff) values (${doctorId(bk, dc)}, ${M.DAYS.indexOf(day)}, ${q(t)});`);
    }
    if (d.consultOverride) {
      const t = arDigits(d.consultOverride);
      const m = t.match(/جلدية (\d+) \/ شعر (\d+) \/ جلدية وشعر (\d+) \/ إعادة (\d+)/);
      if (!m) warn(`[${key}] consultOverride not parsed: ${d.consultOverride}`);
      else [['derma', m[1]], ['hair', m[2]], ['derma_hair', m[3]], ['recons', m[4]]].forEach(([k, v]) => {
        emit(`insert into public.consultation_prices (branch_id, doctor_id, kind, price) values (${branchId(bk)}, ${doctorId(bk, dc)}, ${q(k)}, ${v});`);
      });
    }
    if (d.tempNote) warn(`[${key}] tempNote skipped (expired MVP note): ${d.tempNote}`);
  });
});
Object.keys(M.RULES).forEach((k) => { if (!usedRules.has(k)) warn(`RULES key matched no doctor: ${k}`); });
emit();

// ---------------------------------------------------------------------
// 8) Knowledge base
// ---------------------------------------------------------------------
emit('-- Knowledge base');
M.SERVICES22.forEach((s, i) => {
  emit(`insert into public.kb_articles (slug, kind, title, body, sort) values (${q('service:' + s.id)}, 'service', ${q(s.name)}, ${qJson(s)}, ${i});`);
});
Object.entries(M.DEFS).forEach(([k, d], i) => {
  emit(`insert into public.kb_articles (slug, kind, title, body, sort) values (${q('def:' + k)}, 'definition', ${q(d.title)}, ${qJson(d)}, ${i});`);
});
MANUAL_KEYS.forEach((k, i) => {
  emit(`insert into public.kb_articles (slug, kind, title, body, sort) values (${q('manual:' + k.toLowerCase())}, 'manual', ${q(k)}, ${qJson(M[k])}, ${i});`);
});
emit();
emit('commit;');

process.stdout.write(out.join('\n') + '\n');
